// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steammessages_useraccount.steamclient.proto

#include "steammessages_useraccount.steamclient.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class CUserAccount_GetAccountLinkStatus_RequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CUserAccount_GetAccountLinkStatus_Request>
      _instance;
} _CUserAccount_GetAccountLinkStatus_Request_default_instance_;
class CUserAccount_GetAccountLinkStatus_ResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CUserAccount_GetAccountLinkStatus_Response>
      _instance;
} _CUserAccount_GetAccountLinkStatus_Response_default_instance_;
class CUserAccount_RegisterCompatTool_RequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CUserAccount_RegisterCompatTool_Request>
      _instance;
} _CUserAccount_RegisterCompatTool_Request_default_instance_;
class CUserAccount_RegisterCompatTool_ResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CUserAccount_RegisterCompatTool_Response>
      _instance;
} _CUserAccount_RegisterCompatTool_Response_default_instance_;
namespace protobuf_steammessages_5fuseraccount_2esteamclient_2eproto {
static void InitDefaultsCUserAccount_GetAccountLinkStatus_Request() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_CUserAccount_GetAccountLinkStatus_Request_default_instance_;
    new (ptr) ::CUserAccount_GetAccountLinkStatus_Request();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CUserAccount_GetAccountLinkStatus_Request::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CUserAccount_GetAccountLinkStatus_Request =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCUserAccount_GetAccountLinkStatus_Request}, {}};

static void InitDefaultsCUserAccount_GetAccountLinkStatus_Response() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_CUserAccount_GetAccountLinkStatus_Response_default_instance_;
    new (ptr) ::CUserAccount_GetAccountLinkStatus_Response();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CUserAccount_GetAccountLinkStatus_Response::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CUserAccount_GetAccountLinkStatus_Response =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCUserAccount_GetAccountLinkStatus_Response}, {}};

static void InitDefaultsCUserAccount_RegisterCompatTool_Request() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_CUserAccount_RegisterCompatTool_Request_default_instance_;
    new (ptr) ::CUserAccount_RegisterCompatTool_Request();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CUserAccount_RegisterCompatTool_Request::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CUserAccount_RegisterCompatTool_Request =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCUserAccount_RegisterCompatTool_Request}, {}};

static void InitDefaultsCUserAccount_RegisterCompatTool_Response() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_CUserAccount_RegisterCompatTool_Response_default_instance_;
    new (ptr) ::CUserAccount_RegisterCompatTool_Response();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CUserAccount_RegisterCompatTool_Response::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CUserAccount_RegisterCompatTool_Response =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCUserAccount_RegisterCompatTool_Response}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_CUserAccount_GetAccountLinkStatus_Request.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CUserAccount_GetAccountLinkStatus_Response.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CUserAccount_RegisterCompatTool_Request.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CUserAccount_RegisterCompatTool_Response.base);
}

::google::protobuf::Metadata file_level_metadata[4];
const ::google::protobuf::ServiceDescriptor* file_level_service_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CUserAccount_GetAccountLinkStatus_Request, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CUserAccount_GetAccountLinkStatus_Request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CUserAccount_GetAccountLinkStatus_Response, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CUserAccount_GetAccountLinkStatus_Response, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CUserAccount_GetAccountLinkStatus_Response, pwid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CUserAccount_GetAccountLinkStatus_Response, identity_verification_),
  0,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CUserAccount_RegisterCompatTool_Request, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CUserAccount_RegisterCompatTool_Request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CUserAccount_RegisterCompatTool_Request, compat_tool_),
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CUserAccount_RegisterCompatTool_Response, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CUserAccount_RegisterCompatTool_Response, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 5, sizeof(::CUserAccount_GetAccountLinkStatus_Request)},
  { 5, 12, sizeof(::CUserAccount_GetAccountLinkStatus_Response)},
  { 14, 20, sizeof(::CUserAccount_RegisterCompatTool_Request)},
  { 21, 26, sizeof(::CUserAccount_RegisterCompatTool_Response)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_CUserAccount_GetAccountLinkStatus_Request_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_CUserAccount_GetAccountLinkStatus_Response_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_CUserAccount_RegisterCompatTool_Request_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_CUserAccount_RegisterCompatTool_Response_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "steammessages_useraccount.steamclient.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, file_level_service_descriptors);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n+steammessages_useraccount.steamclient."
      "proto\032,steammessages_unified_base.steamc"
      "lient.proto\"+\n)CUserAccount_GetAccountLi"
      "nkStatus_Request\"Y\n*CUserAccount_GetAcco"
      "untLinkStatus_Response\022\014\n\004pwid\030\001 \001(\r\022\035\n\025"
      "identity_verification\030\002 \001(\r\">\n\'CUserAcco"
      "unt_RegisterCompatTool_Request\022\023\n\013compat"
      "_tool\030\001 \001(\r\"*\n(CUserAccount_RegisterComp"
      "atTool_Response2\352\002\n\013UserAccount\022\220\001\n\024GetA"
      "ccountLinkStatus\022*.CUserAccount_GetAccou"
      "ntLinkStatus_Request\032+.CUserAccount_GetA"
      "ccountLinkStatus_Response\"\037\202\265\030\033Fetches a"
      "ccount link status\022\230\001\n\022RegisterCompatToo"
      "l\022(.CUserAccount_RegisterCompatTool_Requ"
      "est\032).CUserAccount_RegisterCompatTool_Re"
      "sponse\"-\202\265\030)Register intended account us"
      "age of a tool\032-\202\265\030)A service to get user"
      " account informationB\003\200\001\001"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 705);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "steammessages_useraccount.steamclient.proto", &protobuf_RegisterTypes);
  ::protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_steammessages_5fuseraccount_2esteamclient_2eproto

// ===================================================================

void CUserAccount_GetAccountLinkStatus_Request::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CUserAccount_GetAccountLinkStatus_Request::CUserAccount_GetAccountLinkStatus_Request()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::scc_info_CUserAccount_GetAccountLinkStatus_Request.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:CUserAccount_GetAccountLinkStatus_Request)
}
CUserAccount_GetAccountLinkStatus_Request::CUserAccount_GetAccountLinkStatus_Request(const CUserAccount_GetAccountLinkStatus_Request& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CUserAccount_GetAccountLinkStatus_Request)
}

void CUserAccount_GetAccountLinkStatus_Request::SharedCtor() {
}

CUserAccount_GetAccountLinkStatus_Request::~CUserAccount_GetAccountLinkStatus_Request() {
  // @@protoc_insertion_point(destructor:CUserAccount_GetAccountLinkStatus_Request)
  SharedDtor();
}

void CUserAccount_GetAccountLinkStatus_Request::SharedDtor() {
}

void CUserAccount_GetAccountLinkStatus_Request::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CUserAccount_GetAccountLinkStatus_Request::descriptor() {
  ::protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CUserAccount_GetAccountLinkStatus_Request& CUserAccount_GetAccountLinkStatus_Request::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::scc_info_CUserAccount_GetAccountLinkStatus_Request.base);
  return *internal_default_instance();
}


void CUserAccount_GetAccountLinkStatus_Request::Clear() {
// @@protoc_insertion_point(message_clear_start:CUserAccount_GetAccountLinkStatus_Request)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool CUserAccount_GetAccountLinkStatus_Request::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CUserAccount_GetAccountLinkStatus_Request)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:CUserAccount_GetAccountLinkStatus_Request)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CUserAccount_GetAccountLinkStatus_Request)
  return false;
#undef DO_
}

void CUserAccount_GetAccountLinkStatus_Request::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CUserAccount_GetAccountLinkStatus_Request)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CUserAccount_GetAccountLinkStatus_Request)
}

::google::protobuf::uint8* CUserAccount_GetAccountLinkStatus_Request::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CUserAccount_GetAccountLinkStatus_Request)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CUserAccount_GetAccountLinkStatus_Request)
  return target;
}

size_t CUserAccount_GetAccountLinkStatus_Request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CUserAccount_GetAccountLinkStatus_Request)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CUserAccount_GetAccountLinkStatus_Request::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CUserAccount_GetAccountLinkStatus_Request)
  GOOGLE_DCHECK_NE(&from, this);
  const CUserAccount_GetAccountLinkStatus_Request* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CUserAccount_GetAccountLinkStatus_Request>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CUserAccount_GetAccountLinkStatus_Request)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CUserAccount_GetAccountLinkStatus_Request)
    MergeFrom(*source);
  }
}

void CUserAccount_GetAccountLinkStatus_Request::MergeFrom(const CUserAccount_GetAccountLinkStatus_Request& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CUserAccount_GetAccountLinkStatus_Request)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void CUserAccount_GetAccountLinkStatus_Request::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CUserAccount_GetAccountLinkStatus_Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CUserAccount_GetAccountLinkStatus_Request::CopyFrom(const CUserAccount_GetAccountLinkStatus_Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CUserAccount_GetAccountLinkStatus_Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CUserAccount_GetAccountLinkStatus_Request::IsInitialized() const {
  return true;
}

void CUserAccount_GetAccountLinkStatus_Request::Swap(CUserAccount_GetAccountLinkStatus_Request* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CUserAccount_GetAccountLinkStatus_Request::InternalSwap(CUserAccount_GetAccountLinkStatus_Request* other) {
  using std::swap;
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CUserAccount_GetAccountLinkStatus_Request::GetMetadata() const {
  protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CUserAccount_GetAccountLinkStatus_Response::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CUserAccount_GetAccountLinkStatus_Response::kPwidFieldNumber;
const int CUserAccount_GetAccountLinkStatus_Response::kIdentityVerificationFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CUserAccount_GetAccountLinkStatus_Response::CUserAccount_GetAccountLinkStatus_Response()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::scc_info_CUserAccount_GetAccountLinkStatus_Response.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:CUserAccount_GetAccountLinkStatus_Response)
}
CUserAccount_GetAccountLinkStatus_Response::CUserAccount_GetAccountLinkStatus_Response(const CUserAccount_GetAccountLinkStatus_Response& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&pwid_, &from.pwid_,
    static_cast<size_t>(reinterpret_cast<char*>(&identity_verification_) -
    reinterpret_cast<char*>(&pwid_)) + sizeof(identity_verification_));
  // @@protoc_insertion_point(copy_constructor:CUserAccount_GetAccountLinkStatus_Response)
}

void CUserAccount_GetAccountLinkStatus_Response::SharedCtor() {
  ::memset(&pwid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&identity_verification_) -
      reinterpret_cast<char*>(&pwid_)) + sizeof(identity_verification_));
}

CUserAccount_GetAccountLinkStatus_Response::~CUserAccount_GetAccountLinkStatus_Response() {
  // @@protoc_insertion_point(destructor:CUserAccount_GetAccountLinkStatus_Response)
  SharedDtor();
}

void CUserAccount_GetAccountLinkStatus_Response::SharedDtor() {
}

void CUserAccount_GetAccountLinkStatus_Response::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CUserAccount_GetAccountLinkStatus_Response::descriptor() {
  ::protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CUserAccount_GetAccountLinkStatus_Response& CUserAccount_GetAccountLinkStatus_Response::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::scc_info_CUserAccount_GetAccountLinkStatus_Response.base);
  return *internal_default_instance();
}


void CUserAccount_GetAccountLinkStatus_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:CUserAccount_GetAccountLinkStatus_Response)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    ::memset(&pwid_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&identity_verification_) -
        reinterpret_cast<char*>(&pwid_)) + sizeof(identity_verification_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool CUserAccount_GetAccountLinkStatus_Response::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CUserAccount_GetAccountLinkStatus_Response)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 pwid = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_pwid();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &pwid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 identity_verification = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_identity_verification();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &identity_verification_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CUserAccount_GetAccountLinkStatus_Response)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CUserAccount_GetAccountLinkStatus_Response)
  return false;
#undef DO_
}

void CUserAccount_GetAccountLinkStatus_Response::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CUserAccount_GetAccountLinkStatus_Response)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 pwid = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->pwid(), output);
  }

  // optional uint32 identity_verification = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->identity_verification(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CUserAccount_GetAccountLinkStatus_Response)
}

::google::protobuf::uint8* CUserAccount_GetAccountLinkStatus_Response::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CUserAccount_GetAccountLinkStatus_Response)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 pwid = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->pwid(), target);
  }

  // optional uint32 identity_verification = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->identity_verification(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CUserAccount_GetAccountLinkStatus_Response)
  return target;
}

size_t CUserAccount_GetAccountLinkStatus_Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CUserAccount_GetAccountLinkStatus_Response)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional uint32 pwid = 1;
    if (has_pwid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->pwid());
    }

    // optional uint32 identity_verification = 2;
    if (has_identity_verification()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->identity_verification());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CUserAccount_GetAccountLinkStatus_Response::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CUserAccount_GetAccountLinkStatus_Response)
  GOOGLE_DCHECK_NE(&from, this);
  const CUserAccount_GetAccountLinkStatus_Response* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CUserAccount_GetAccountLinkStatus_Response>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CUserAccount_GetAccountLinkStatus_Response)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CUserAccount_GetAccountLinkStatus_Response)
    MergeFrom(*source);
  }
}

void CUserAccount_GetAccountLinkStatus_Response::MergeFrom(const CUserAccount_GetAccountLinkStatus_Response& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CUserAccount_GetAccountLinkStatus_Response)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      pwid_ = from.pwid_;
    }
    if (cached_has_bits & 0x00000002u) {
      identity_verification_ = from.identity_verification_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void CUserAccount_GetAccountLinkStatus_Response::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CUserAccount_GetAccountLinkStatus_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CUserAccount_GetAccountLinkStatus_Response::CopyFrom(const CUserAccount_GetAccountLinkStatus_Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CUserAccount_GetAccountLinkStatus_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CUserAccount_GetAccountLinkStatus_Response::IsInitialized() const {
  return true;
}

void CUserAccount_GetAccountLinkStatus_Response::Swap(CUserAccount_GetAccountLinkStatus_Response* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CUserAccount_GetAccountLinkStatus_Response::InternalSwap(CUserAccount_GetAccountLinkStatus_Response* other) {
  using std::swap;
  swap(pwid_, other->pwid_);
  swap(identity_verification_, other->identity_verification_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CUserAccount_GetAccountLinkStatus_Response::GetMetadata() const {
  protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CUserAccount_RegisterCompatTool_Request::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CUserAccount_RegisterCompatTool_Request::kCompatToolFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CUserAccount_RegisterCompatTool_Request::CUserAccount_RegisterCompatTool_Request()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::scc_info_CUserAccount_RegisterCompatTool_Request.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:CUserAccount_RegisterCompatTool_Request)
}
CUserAccount_RegisterCompatTool_Request::CUserAccount_RegisterCompatTool_Request(const CUserAccount_RegisterCompatTool_Request& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  compat_tool_ = from.compat_tool_;
  // @@protoc_insertion_point(copy_constructor:CUserAccount_RegisterCompatTool_Request)
}

void CUserAccount_RegisterCompatTool_Request::SharedCtor() {
  compat_tool_ = 0u;
}

CUserAccount_RegisterCompatTool_Request::~CUserAccount_RegisterCompatTool_Request() {
  // @@protoc_insertion_point(destructor:CUserAccount_RegisterCompatTool_Request)
  SharedDtor();
}

void CUserAccount_RegisterCompatTool_Request::SharedDtor() {
}

void CUserAccount_RegisterCompatTool_Request::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CUserAccount_RegisterCompatTool_Request::descriptor() {
  ::protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CUserAccount_RegisterCompatTool_Request& CUserAccount_RegisterCompatTool_Request::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::scc_info_CUserAccount_RegisterCompatTool_Request.base);
  return *internal_default_instance();
}


void CUserAccount_RegisterCompatTool_Request::Clear() {
// @@protoc_insertion_point(message_clear_start:CUserAccount_RegisterCompatTool_Request)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  compat_tool_ = 0u;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool CUserAccount_RegisterCompatTool_Request::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CUserAccount_RegisterCompatTool_Request)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 compat_tool = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_compat_tool();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &compat_tool_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CUserAccount_RegisterCompatTool_Request)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CUserAccount_RegisterCompatTool_Request)
  return false;
#undef DO_
}

void CUserAccount_RegisterCompatTool_Request::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CUserAccount_RegisterCompatTool_Request)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 compat_tool = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->compat_tool(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CUserAccount_RegisterCompatTool_Request)
}

::google::protobuf::uint8* CUserAccount_RegisterCompatTool_Request::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CUserAccount_RegisterCompatTool_Request)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 compat_tool = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->compat_tool(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CUserAccount_RegisterCompatTool_Request)
  return target;
}

size_t CUserAccount_RegisterCompatTool_Request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CUserAccount_RegisterCompatTool_Request)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // optional uint32 compat_tool = 1;
  if (has_compat_tool()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->compat_tool());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CUserAccount_RegisterCompatTool_Request::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CUserAccount_RegisterCompatTool_Request)
  GOOGLE_DCHECK_NE(&from, this);
  const CUserAccount_RegisterCompatTool_Request* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CUserAccount_RegisterCompatTool_Request>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CUserAccount_RegisterCompatTool_Request)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CUserAccount_RegisterCompatTool_Request)
    MergeFrom(*source);
  }
}

void CUserAccount_RegisterCompatTool_Request::MergeFrom(const CUserAccount_RegisterCompatTool_Request& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CUserAccount_RegisterCompatTool_Request)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_compat_tool()) {
    set_compat_tool(from.compat_tool());
  }
}

void CUserAccount_RegisterCompatTool_Request::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CUserAccount_RegisterCompatTool_Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CUserAccount_RegisterCompatTool_Request::CopyFrom(const CUserAccount_RegisterCompatTool_Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CUserAccount_RegisterCompatTool_Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CUserAccount_RegisterCompatTool_Request::IsInitialized() const {
  return true;
}

void CUserAccount_RegisterCompatTool_Request::Swap(CUserAccount_RegisterCompatTool_Request* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CUserAccount_RegisterCompatTool_Request::InternalSwap(CUserAccount_RegisterCompatTool_Request* other) {
  using std::swap;
  swap(compat_tool_, other->compat_tool_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CUserAccount_RegisterCompatTool_Request::GetMetadata() const {
  protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CUserAccount_RegisterCompatTool_Response::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CUserAccount_RegisterCompatTool_Response::CUserAccount_RegisterCompatTool_Response()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::scc_info_CUserAccount_RegisterCompatTool_Response.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:CUserAccount_RegisterCompatTool_Response)
}
CUserAccount_RegisterCompatTool_Response::CUserAccount_RegisterCompatTool_Response(const CUserAccount_RegisterCompatTool_Response& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CUserAccount_RegisterCompatTool_Response)
}

void CUserAccount_RegisterCompatTool_Response::SharedCtor() {
}

CUserAccount_RegisterCompatTool_Response::~CUserAccount_RegisterCompatTool_Response() {
  // @@protoc_insertion_point(destructor:CUserAccount_RegisterCompatTool_Response)
  SharedDtor();
}

void CUserAccount_RegisterCompatTool_Response::SharedDtor() {
}

void CUserAccount_RegisterCompatTool_Response::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CUserAccount_RegisterCompatTool_Response::descriptor() {
  ::protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CUserAccount_RegisterCompatTool_Response& CUserAccount_RegisterCompatTool_Response::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::scc_info_CUserAccount_RegisterCompatTool_Response.base);
  return *internal_default_instance();
}


void CUserAccount_RegisterCompatTool_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:CUserAccount_RegisterCompatTool_Response)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool CUserAccount_RegisterCompatTool_Response::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CUserAccount_RegisterCompatTool_Response)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:CUserAccount_RegisterCompatTool_Response)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CUserAccount_RegisterCompatTool_Response)
  return false;
#undef DO_
}

void CUserAccount_RegisterCompatTool_Response::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CUserAccount_RegisterCompatTool_Response)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CUserAccount_RegisterCompatTool_Response)
}

::google::protobuf::uint8* CUserAccount_RegisterCompatTool_Response::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CUserAccount_RegisterCompatTool_Response)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CUserAccount_RegisterCompatTool_Response)
  return target;
}

size_t CUserAccount_RegisterCompatTool_Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CUserAccount_RegisterCompatTool_Response)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CUserAccount_RegisterCompatTool_Response::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CUserAccount_RegisterCompatTool_Response)
  GOOGLE_DCHECK_NE(&from, this);
  const CUserAccount_RegisterCompatTool_Response* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CUserAccount_RegisterCompatTool_Response>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CUserAccount_RegisterCompatTool_Response)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CUserAccount_RegisterCompatTool_Response)
    MergeFrom(*source);
  }
}

void CUserAccount_RegisterCompatTool_Response::MergeFrom(const CUserAccount_RegisterCompatTool_Response& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CUserAccount_RegisterCompatTool_Response)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void CUserAccount_RegisterCompatTool_Response::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CUserAccount_RegisterCompatTool_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CUserAccount_RegisterCompatTool_Response::CopyFrom(const CUserAccount_RegisterCompatTool_Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CUserAccount_RegisterCompatTool_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CUserAccount_RegisterCompatTool_Response::IsInitialized() const {
  return true;
}

void CUserAccount_RegisterCompatTool_Response::Swap(CUserAccount_RegisterCompatTool_Response* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CUserAccount_RegisterCompatTool_Response::InternalSwap(CUserAccount_RegisterCompatTool_Response* other) {
  using std::swap;
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CUserAccount_RegisterCompatTool_Response::GetMetadata() const {
  protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

UserAccount::~UserAccount() {}

const ::google::protobuf::ServiceDescriptor* UserAccount::descriptor() {
  protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::file_level_service_descriptors[0];
}

const ::google::protobuf::ServiceDescriptor* UserAccount::GetDescriptor() {
  return descriptor();
}

void UserAccount::GetAccountLinkStatus(::google::protobuf::RpcController* controller,
                         const ::CUserAccount_GetAccountLinkStatus_Request*,
                         ::CUserAccount_GetAccountLinkStatus_Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method GetAccountLinkStatus() not implemented.");
  done->Run();
}

void UserAccount::RegisterCompatTool(::google::protobuf::RpcController* controller,
                         const ::CUserAccount_RegisterCompatTool_Request*,
                         ::CUserAccount_RegisterCompatTool_Response*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method RegisterCompatTool() not implemented.");
  done->Run();
}

void UserAccount::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), protobuf_steammessages_5fuseraccount_2esteamclient_2eproto::file_level_service_descriptors[0]);
  switch(method->index()) {
    case 0:
      GetAccountLinkStatus(controller,
             ::google::protobuf::down_cast<const ::CUserAccount_GetAccountLinkStatus_Request*>(request),
             ::google::protobuf::down_cast< ::CUserAccount_GetAccountLinkStatus_Response*>(response),
             done);
      break;
    case 1:
      RegisterCompatTool(controller,
             ::google::protobuf::down_cast<const ::CUserAccount_RegisterCompatTool_Request*>(request),
             ::google::protobuf::down_cast< ::CUserAccount_RegisterCompatTool_Response*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& UserAccount::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::CUserAccount_GetAccountLinkStatus_Request::default_instance();
    case 1:
      return ::CUserAccount_RegisterCompatTool_Request::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::google::protobuf::Message& UserAccount::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::CUserAccount_GetAccountLinkStatus_Response::default_instance();
    case 1:
      return ::CUserAccount_RegisterCompatTool_Response::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

UserAccount_Stub::UserAccount_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
UserAccount_Stub::UserAccount_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
UserAccount_Stub::~UserAccount_Stub() {
  if (owns_channel_) delete channel_;
}

void UserAccount_Stub::GetAccountLinkStatus(::google::protobuf::RpcController* controller,
                              const ::CUserAccount_GetAccountLinkStatus_Request* request,
                              ::CUserAccount_GetAccountLinkStatus_Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void UserAccount_Stub::RegisterCompatTool(::google::protobuf::RpcController* controller,
                              const ::CUserAccount_RegisterCompatTool_Request* request,
                              ::CUserAccount_RegisterCompatTool_Response* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::CUserAccount_GetAccountLinkStatus_Request* Arena::CreateMaybeMessage< ::CUserAccount_GetAccountLinkStatus_Request >(Arena* arena) {
  return Arena::CreateInternal< ::CUserAccount_GetAccountLinkStatus_Request >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::CUserAccount_GetAccountLinkStatus_Response* Arena::CreateMaybeMessage< ::CUserAccount_GetAccountLinkStatus_Response >(Arena* arena) {
  return Arena::CreateInternal< ::CUserAccount_GetAccountLinkStatus_Response >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::CUserAccount_RegisterCompatTool_Request* Arena::CreateMaybeMessage< ::CUserAccount_RegisterCompatTool_Request >(Arena* arena) {
  return Arena::CreateInternal< ::CUserAccount_RegisterCompatTool_Request >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::CUserAccount_RegisterCompatTool_Response* Arena::CreateMaybeMessage< ::CUserAccount_RegisterCompatTool_Response >(Arena* arena) {
  return Arena::CreateInternal< ::CUserAccount_RegisterCompatTool_Response >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
