// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steammessages_unified_base.steamclient.proto

#include "steammessages_unified_base.steamclient.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class NoResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NoResponse>
      _instance;
} _NoResponse_default_instance_;
namespace protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto {
static void InitDefaultsNoResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_NoResponse_default_instance_;
    new (ptr) ::NoResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::NoResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_NoResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsNoResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_NoResponse.base);
}

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NoResponse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::NoResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 5, sizeof(::NoResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_NoResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "steammessages_unified_base.steamclient.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n,steammessages_unified_base.steamclient"
      ".proto\032 google/protobuf/descriptor.proto"
      "\"\014\n\nNoResponse*]\n\023EProtoExecutionSite\022 \n"
      "\034k_EProtoExecutionSiteUnknown\020\000\022$\n k_EPr"
      "otoExecutionSiteSteamClient\020\002:4\n\013descrip"
      "tion\022\035.google.protobuf.FieldOptions\030\320\206\003 "
      "\001(\t:>\n\023service_description\022\037.google.prot"
      "obuf.ServiceOptions\030\320\206\003 \001(\t:u\n\026service_e"
      "xecution_site\022\037.google.protobuf.ServiceO"
      "ptions\030\330\206\003 \001(\0162\024.EProtoExecutionSite:\034k_"
      "EProtoExecutionSiteUnknown:<\n\022method_des"
      "cription\022\036.google.protobuf.MethodOptions"
      "\030\320\206\003 \001(\t:8\n\020enum_description\022\034.google.pr"
      "otobuf.EnumOptions\030\320\206\003 \001(\t:C\n\026enum_value"
      "_description\022!.google.protobuf.EnumValue"
      "Options\030\320\206\003 \001(\tB\005H\001\200\001\000"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 622);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "steammessages_unified_base.steamclient.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2fdescriptor_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto
const ::google::protobuf::EnumDescriptor* EProtoExecutionSite_descriptor() {
  protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::file_level_enum_descriptors[0];
}
bool EProtoExecutionSite_IsValid(int value) {
  switch (value) {
    case 0:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void NoResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NoResponse::NoResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::scc_info_NoResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:NoResponse)
}
NoResponse::NoResponse(const NoResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:NoResponse)
}

void NoResponse::SharedCtor() {
}

NoResponse::~NoResponse() {
  // @@protoc_insertion_point(destructor:NoResponse)
  SharedDtor();
}

void NoResponse::SharedDtor() {
}

void NoResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* NoResponse::descriptor() {
  ::protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NoResponse& NoResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::scc_info_NoResponse.base);
  return *internal_default_instance();
}


void NoResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:NoResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool NoResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:NoResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:NoResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:NoResponse)
  return false;
#undef DO_
}

void NoResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:NoResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:NoResponse)
}

::google::protobuf::uint8* NoResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:NoResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NoResponse)
  return target;
}

size_t NoResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NoResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NoResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NoResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const NoResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NoResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NoResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NoResponse)
    MergeFrom(*source);
  }
}

void NoResponse::MergeFrom(const NoResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NoResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void NoResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NoResponse::CopyFrom(const NoResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NoResponse::IsInitialized() const {
  return true;
}

void NoResponse::Swap(NoResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NoResponse::InternalSwap(NoResponse* other) {
  using std::swap;
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata NoResponse::GetMetadata() const {
  protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_steammessages_5funified_5fbase_2esteamclient_2eproto::file_level_metadata[kIndexInFileMessages];
}

const ::std::string description_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  description(kDescriptionFieldNumber, description_default);
const ::std::string service_description_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  service_description(kServiceDescriptionFieldNumber, service_description_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::EnumTypeTraits< ::EProtoExecutionSite, ::EProtoExecutionSite_IsValid>, 14, false >
  service_execution_site(kServiceExecutionSiteFieldNumber, static_cast< ::EProtoExecutionSite >(0));
const ::std::string method_description_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  method_description(kMethodDescriptionFieldNumber, method_description_default);
const ::std::string enum_description_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  enum_description(kEnumDescriptionFieldNumber, enum_description_default);
const ::std::string enum_value_description_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  enum_value_description(kEnumValueDescriptionFieldNumber, enum_value_description_default);

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::NoResponse* Arena::CreateMaybeMessage< ::NoResponse >(Arena* arena) {
  return Arena::CreateInternal< ::NoResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
